name: QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install latest Yarn
        run: corepack prepare yarn@4 --activate
      - name: Activate latest Yarn
        run: yarn set version 4
      - name: Install dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test